#! /bin/sh
# /etc/init.d/k9webdaemon 

### BEGIN INIT INFO
# Provides:          k9webdaemon 
# Required-Start:    $syslog $k9pidaemon
# Required-Stop:     $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts up web server communication to the k9 robot
# Description:       Reponsible for auto starting the web server for k9 robot. A script which will start / stop a program a boot / shutdown.
### END INIT INFO

# See http://blog.scphillips.com/2013/07/getting-a-python-script-to-run-in-the-background-as-a-service-on-boot/

    PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
    DAEMON=/home/pi/projects/k9os/pi/web/k9webserver.py
    PYTHONPATH=/home/pi/projects/k9os/pi/lib
    NAME=k9webdaemon
    DESC="K9 Web Communications Daemon"

    test -x $DAEMON || exit 0

    . /lib/lsb/init-functions

    set -e

    case "$1" in
      start)
        echo -n "Starting $DESC: "
        start-stop-daemon --start --quiet --pidfile /var/run/$NAME.pid --background --make-pidfile --exec $DAEMON
        echo "$NAME."
        ;;
      stop)
        echo -n "Stopping $DESC: "
        start-stop-daemon --stop --oknodo --quiet --pidfile /var/run/$NAME.pid
        echo "$NAME."
        ;;
      restart)
        $0 stop
        sleep 1
        $0 start
        ;;
      *)
        echo "Usage: $0 {start|stop|restart}" >&2
        exit 1
        ;;
    esac
    exit 0
