#! /bin/sh
# /etc/init.d/k9pidaemon 

### BEGIN INIT INFO
# Provides:          k9pidaemon 
# Required-Start:    alsa-utils
# Required-Stop:     alsa-utils
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts up serial communication to the k9 robot
# Description:       Reponsible for auto starting the k9 robot. A script which will start / stop a program a boot / shutdown.
### END INIT INFO

    PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
    DAEMON=/home/pi/projects/k9os/pi/daemon/rpc_daemon.py
    PYTHONPATH=/home/pi/projects/k9os/pi/lib
    NAME=pik9comm
    DESC="K9 Serial Communications Daemon"

    test -x $DAEMON || exit 0

    . /lib/lsb/init-functions

    set -e

    case "$1" in
      start)
        echo -n "Starting $DESC: "
        start-stop-daemon --start --quiet --pidfile /var/run/$NAME.pid --background --make-pidfile --exec $DAEMON
        echo "$NAME."
        ;;
      stop)
        echo -n "Stopping $DESC: "
        start-stop-daemon --stop --oknodo --quiet --pidfile /var/run/$NAME.pid
        echo "$NAME."
        ;;
      restart)
        $0 stop
        sleep 1
        $0 start
        ;;
      *)
        echo "Usage: $0 {start|stop|restart}" >&2
        exit 1
        ;;
    esac
    exit 0
