#!/bin/sh
stty -F/dev/serial/by-path/platform-bcm2708_usb-usb-0:1.3:1.0-port0 cs8 115200 ignbrk -brkint -imaxbel -opost -onlcr -isig -icanon -iexten -echo -echoe -echok -echoctl -echoke noflsh -ixon -crtscts
screen /dev/serial/by-path/platform-bcm2708_usb-usb-0:1.3:1.0-port0 115200
