#!/bin/sh
USB_PORT=/dev/serial/by-path/platform-bcm2708_usb-usb-0:1.3.2:1.0
stty -F$USB_PORT cs8 115200 ignbrk -brkint -imaxbel -opost -onlcr -isig -icanon -iexten -echo -echoe -echok -echoctl -echoke noflsh -ixon -crtscts
screen $USB_PORT 115200
